name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'Go Releaser'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build Release
        run: |
          ./build.sh release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: compress/*
          prerelease: false
